version: '3.6'

services:
  mainnet:
    image: realnuts\docker_litecoind:0.18.1-0
    restart: always
    user: root
    command: litecoind
    ports:
      - "9332:9332"
    volumes:
      - /opt/litecoin/keys/mainnet:/litecoin/wallet
      - /opt/litecoin/blocks/mainnet:/litecoin/.litecoin/blocks
      - /opt/litecoin/config/mainnet.conf:/litecoin/.litecoin/litecoin.conf

  testnet:
    image: quay.io/openware/litecoin:0.17.1
    restart: always
    user: root
    command: litecoind
    ports:
      - "19332:19332"
    volumes:
      - /opt/litecoin/keys/testnet:/litecoin/wallet
      - /opt/litecoin/blocks/testnet:/litecoin/.litecoin/testnet3/blocks
      - /opt/litecoin/config/testnet.conf:/home/litecoin/.litecoin/litecoin.conf
